apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ecs
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      name: "http"
      targetPort: 8080
      protocol: TCP
    - port: 50000
      name: "agent"
      protocol: TCP
  selector:
    app: jenkins